### ISSUE TITLE
How to check original JS files rather than module-transpiler processed files?

### ISSUE THREAD

**Issue by ivanvotti** [kellyselden/broccoli-jscs#10]
@rwjblue I get irrelevant JSCS reports about code style issues in module-transpiler processed files. I'd like JSCS to check code style in original source files only. How can I do that?

Example of JSCS noise:
```
Use dot notation instead of brackets for member expressions at webclient/initializers/wallets.js :
    14 |  }, function() {
    15 |    walletManager = false;
    16 |  })["finally"](function() {
-------------^
```

But in the original file I don't have any code style problems:
```
  }, function() {
    walletManager = false;
  }).finally(function() {
```

**Comment by rwjblue** [comment]
you only pass pre-transpiled source to the main filter

**Comment by ivanvotti** [comment]
can you give me an example please? It's still very hard for me to understand broccoli and ember-cli plugins system.

**Comment by rwjblue** [comment]
Should be fixable once https://github.com/ember-cli/ember-cli/pull/3094 lands (and once we update to use the `postprocessTree` hook like https://github.com/ember-cli/ember-cli-qunit/pull/28).

**Comment by knownasilya** [comment]
:+1: Looks like this will be in soon, sweet.

**Comment by rwjblue** [comment]
@knownasilya - Ya, I should get a PR together tonight/tomorrow morning.

**Comment by ivanvotti** [comment]
@rwjblue - Is it already possible to fix the issue?

**Comment by rwjblue** [comment]
Yes, this should already be resolved.

**Comment by kellyselden** [comment]
@ivanvotti Can you confirm this is fixed?

**Comment by ivanvotti** [comment]
@rwjblue @kellyselden I've just tried `broccoli-jscs` `v.1.1.0` and can confirm it's fixed. Thank you.
