### ISSUE TITLE
`enabled: false` should not create a `JSCSFilter` instance

### ISSUE THREAD

**Issue by zeppelin** [kellyselden/broccoli-jscs#23]
The issue I ran into recently was a failing `ember build` command after an `npm install` due to a custom JSCS rule that became incompatible with `jscs@1.12.0`. It took me days to isolate the problem, because I thought `enabled: false` will completely disable the addon.

Regardless of my issue, it seems that currently it adds a slight perf hit to the app when it's disabled, since JSCS will run regardless the `enabled` setting: https://github.com/kellyselden/broccoli-jscs/blob/master/ember-addon-main.js#L14-L18

If checking the `enabled` flag and returning the untouched tree immediately before running the filter sounds good, I'll submit a PR with the changes.

**Comment by kellyselden** [comment]
Sounds good to me. Thanks
