### ISSUE TITLE
Caching issue when running npm test?

### ISSUE THREAD

**Issue by amyrlam** [kellyselden/broccoli-jscs#53]
Reference: https://github.com/dockyard/ember-suave/issues/94

I've been using ember-suave quite a bit and found some issues when running `npm test`. Context:

I run a `npm test`locally to see what I should fix re: ember-suave. Then fix the code. 

I run `npm test` locally again and get a passing test suite (Note: `not ok 1405` is an unrelated error that I'm debugging...):

```
...
ok 1401 PhantomJS 1.9 - JSCS - unit/utils: unit/utils/role-among-test.js should pass jscs
ok 1402 PhantomJS 1.9 - JSHint - unit/utils: unit/utils/role-among-test.js should pass jshint
ok 1403 PhantomJS 1.9 - roleAtLeast macro: returns false if session.user is not a user
ok 1404 PhantomJS 1.9 - roleAtLeast macro: returns false if session.user does not have the role
not ok 1405 PhantomJS - Browser "phantomjs /Users/alam/src/Tango/node_modules/ember-cli/node_modules/testem/assets/phantom.js http://localhost:7357/3320" exited unexpectedly.

1..1405
# tests 1405
# pass  1404
# fail  1
npm ERR! Test failed.  See above for more details.
```

I push my code to GitHub and the build fails on Travis. Why wasn't the local `npm test` the same? 

```
...
disallowVar: Variable declarations should use `let` or `const` not `var` at acceptance/configure/conditions/gzip-conditions-test.js :
     9 |const { merge } = Ember;
    10 |
    11 |var application;
--------^
    12 |var cacheConditionSpecificAttrs;
    13 |var contentsRouteUrl;
disallowVar: Variable declarations should use `let` or `const` not `var` at acceptance/configure/conditions/gzip-conditions-test.js :
    10 |
    11 |var application;
    12 |var cacheConditionSpecificAttrs;
--------^
    13 |var contentsRouteUrl;
    14 |var gzipRouteUrl;
disallowVar: Variable declarations should use `let` or `const` not `var` at acceptance/configure/conditions/gzip-conditions-test.js :
...
1..1466
# tests 1466
# pass  1460
# fail  6
```

Maybe related, I've noticed that when I'm changing the `.jscsrc`, the first time I run `npm test` locally, I'll get these JSCS `disallowVar` errors at the top, before `npm test` starts going through all the numbers of tests:

```
disallowVar: Variable declarations should use `let` or `const` not `var` at acceptance/configure/conditions/gzip-conditions-test.js :
     9 |const { merge } = Ember;
    10 |
    11 |var application;
--------^
    12 |var cacheConditionSpecificAttrs;
    13 |var contentsRouteUrl;
```

**But the second or third time I run `npm test` locally after changing code to fix the rule I've edited in the `.jscsrc`, I don't get these JSCS `disallowVar` errors at the top, it just starts with the numbered tests** e.g. 

```
npm test

> tango@0.0.0 test /Users/alam/src/Tango
> ember test

version: 1.13.12
Building[Deprecated] new this.Funnel(..) is deprecated, please use broccoli-funnel directly instead  [addon: ember-modal-dialog]
[Deprecated] new this.Funnel(..) is deprecated, please use broccoli-funnel directly instead  [addon: ember-tooltips]
Building..Warning: ignoring input sourcemap for bower_components/ember/ember-template-compiler.js because ENOENT: no such file or directory, open '/Users/alam/src/Tango/tmp/concat_with_maps-input_base_path-wN2UTJOc.tmp/0/bower_components/ember/ember-template-compiler.map'
Built project successfully. Stored in "/Users/alam/src/Tango/tmp/class-tests_dist-ELMgJtJA.tmp".
ok 1 PhantomJS 1.9 - JSCS - abilities: abilities/all.js should pass jscs
ok 2 PhantomJS 1.9 - JSHint - abilities: abilities/all.js should pass jshint
ok 3 PhantomJS 1.9 - Acceptance: account/index/2fa-disable:
  As a User with 2FA enabled, I can disable it when entering a valid
  Authentication Code
```

I've also noticed that if number of JSCS errors is high, the list of JSCS errors e.g.

```
disallowVar: Variable declarations should use `let` or `const` not `var` at acceptance/configure/conditions/gzip-conditions-test.js :
     9 |const { merge } = Ember;
    10 |
    11 |var application;
--------^
    12 |var cacheConditionSpecificAttrs;
    13 |var contentsRouteUrl;
```

before the list of numbers for my tests cuts off, without signaling that it's cut off. But on a subsequent push to Travis, subsequent JSCS errors will populate before the numbered test portion of the build.

I know this is a little confusing, let me know if you need more info.

**Comment by rwjblue** [comment]
We should be busting the cache when the .jscsrc file changes (see https://github.com/kellyselden/broccoli-jscs/blob/master/index.js#L150), but I suspect there is an issue here.

**Comment by adam-knights** [comment]
Just as a FYI I saw a weird issue today where I added the rule `"requireEnhancedObjectLiterals": true`, then restarted Ember CLI - it caused some JSCS tests to fail but not all of them that should of been. Once I cleaned out bower and npm directories and re downloaded everything the rest then showed up.

**Comment by kellyselden** [comment]
@amyrlam Can you please try v1.3.0?

**Comment by amyrlam** [comment]
I'll test v1.3.0 out likely tmrw, sorry for the delay.

**Comment by amyrlam** [comment]
v1.3.0 didn't work for me. 

Updated ember-suave to 2.0.1, manually set broccoli-jscs to 1.3.0 in my local node_modules/ember-suave/package.json. 

Made some changes locally and ran `npm test` a few times, e.g. 

* Set new rule `disallowEmberKeys: null` in `.jscsrc` and run `npm test` - failures in terminal
* Remove `disallowEmberKeys: null` in `.jscsrc` and run `npm test` again - no failures in terminal, but see failures such as below when pushed to GitHub and run in Travis CI

```
disallowEmberKeys: Ember.keys is deprecated in Ember 1.13 at utils/persisted-value.js :
    52 |
    53 |    const changedAttrs = record.changedAttributes();
    54 |    if (Ember.keys(changedAttrs).indexOf(propertyPath) !== -1) {
----------------------^
    55 |      return changedAttrs[propertyPath][0];
    56 |    }
mkdir -p /home/travis/build/fastly/Tango/tmp/srihash_assets-output_path-HKKqCwK3.tmp/index
cp /home/travis/build/fastly/Tango/tmp/srihash_assets-output_path-HKKqCwK3.tmp/index.html /home/travis/build/fastly/Tango/tmp/srihash_assets-output_path-HKKqCwK3.tmp/index/staging-6623.html
rm /home/travis/build/fastly/Tango/tmp/srihash_assets-output_path-HKKqCwK3.tmp/index.html
Built project successfully. Stored in "/home/travis/build/fastly/Tango/tmp/class-tests_dist-Jq40FYn4.tmp".
ok 1 PhantomJS 2.1 - JSCS - abilities: abilities/all.js should pass jscs
ok 2 PhantomJS 2.1 - JSHint - abilities: abilities/all.js should pass jshint
...

**Comment by amyrlam** [comment]
I haven't seen this issue in some time, it seems safe to close. Feel free to reopen if I'm wrong!
