### ISSUE TITLE
Ember CLI show JSCS errors on every build

### ISSUE THREAD

**Issue by ashblue** [kellyselden/broccoli-jscs#57]
My team wants JSCS to fire on every build. Only seems to fire on the first initial build though with Ember CLI. Is there a way to make this happen?

**Comment by kellyselden** [comment]
I believe this is the same bug as #53.

**Comment by ashblue** [comment]
Thanks for the fast response. This is the only thing holding us back from using the library in our workflow. Will patiently await a bugfix.
