### ISSUE TITLE
Is there any way to exclude particular js files?

### ISSUE THREAD

**Issue by ivanvotti** [kellyselden/broccoli-jscs#6]
For example, I'd like to exclude all files in `app/tests/` dir. Currently I'm doing it with `broccoli-funnel` like this: https://github.com/ivanvotti/broccoli-jscs/commit/19d6619d1cc99f15115bba88cec5aa7196b281cf. @rwjblue Is it a right way for this case?

To exclude all test files I have this in `Brocfile.js`:
```
var app = new EmberApp({
  jscsOptions: {
    excludeFiles: ['webclient/tests/**']
  }
});
```

**Comment by rwjblue** [comment]
@ivanvotti - Yep, this is right.  You can also add your excludes to `.jscsrc` file (like I did here: https://github.com/emberjs/ember.js/blob/master/.jscsrc#L3).

**Comment by ivanvotti** [comment]
@rwjblue I tried to use that way too but It didn't work for me.

**Comment by rwjblue** [comment]
Ahh, I see. Yes, the support I added in https://github.com/kellyselden/broccoli-jscs/pull/4 only supported static file names (not globs).

**Comment by ivanvotti** [comment]
Thank you.

**Comment by rwjblue** [comment]
https://github.com/kellyselden/broccoli-jscs/pull/13 should have solved @ivanvotti's scenario (allowing globs).  This can likely be closed...

**Comment by kellyselden** [comment]
closing
