### ISSUE TITLE
add changelog

### ISSUE THREAD

**Issue by kellyselden** [kellyselden/broccoli-jscs#62]
start with letting people know they can remove their custom mocha test generator and use our built in one.

**Comment by Turbo87** [comment]
as a start I've tagged all the release commits in this repo and pushed them to my fork: https://github.com/Turbo87/broccoli-jscs/tags

feel free to give my push access here, then I'll update them here as well.

**Comment by kellyselden** [comment]
Awesome. added you!

**Comment by Turbo87** [comment]
done

**Comment by kellyselden** [comment]
@Turbo87 dang, you're fast!

**Comment by kellyselden** [comment]
resolved in #63

**Comment by Turbo87** [comment]
should've started creating the tags at the bottom though. now the order is all messed up :-/
