### ISSUE TITLE
Doesn't work for Ember Addon if you don't specify configPath in ember-cli-build.js

### ISSUE THREAD

**Issue by nagits** [kellyselden/broccoli-jscs#65]
v1.2.2 works, but for v1.3.0 `ember test` doesn't run jscs, if you don't specify configPath in ember-cli-build.js.

jscs v2.10.1

**Comment by kellyselden** [comment]
cc @Turbo87

**Comment by Turbo87** [comment]
yeah, meant to come back to this, but haven't found the time yet :-/

**Comment by kellyselden** [comment]
Just released v1.3.1. Can you try to see if it is fixed for you @nagits?

**Comment by nagits** [comment]
Yes, it's fixed! Thanks!
