### ISSUE TITLE
Could you please publish a new version?

### ISSUE THREAD

**Issue by alexBaizeau** [kellyselden/broccoli-jscs#79]
I'd like to be able to take advantage of the perf improvement brought by this PR https://github.com/kellyselden/broccoli-jscs/pull/71

Cheers

**Comment by kellyselden** [comment]
I'm going to make time to do this soon.

**Comment by alexBaizeau** [comment]
Thanks a lot

**Comment by kellyselden** [comment]
Released v2.0.0 in #80.
