### ISSUE TITLE
Upgrade broccoli-jscs to remove minimatch@2.0.10, jscs-preset-wikimedia@1.0.1, nomnom@1.8.1

### ISSUE THREAD

**Issue by jacopolanzoni** [kellyselden/broccoli-jscs#88]
Can you please upgrade the broccoli-jscs  dependencies to tackle the following npm install warnings?

npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated jscs-preset-wikimedia@1.0.1: Deprecated in favour of eslint-config-wikimedia. -- https://phabricator.wikimedia.org/T118941
npm WARN deprecated nomnom@1.8.1: Package no longer supported. Contact support@npmjs.com for more info.

**Comment by kellyselden** [comment]
https://github.com/kellyselden/broccoli-jscs#jscs-was-merged-into-eslint-so-this-project-is-no-longer-being-worked-on

I'm not using this anymore, but I will merge pull requests.
